version: "3.7"

services:
  interview_backend_coop_logistics:
    build: .
    container_name: interview_backend_coop_logistics
    environment:
      - APP_PORT=50051
    tty: true
    ports:
      - "50051:50051"
  techdocs:
    build:
      context: internal/techdocs
      dockerfile: Dockerfile
      target: techdocs
    working_dir: /srv/workspace
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-}
      GCLOUD_PROJECT: ${GCLOUD_PROJECT:-}
    volumes:
      - .:/srv/workspace:z
      - ${XDG_CACHE_HOME:-xdg-cache-home}:/root/.cache
      - $HOME/.config/gcloud:/root/.config/gcloud
      - ${GOOGLE_APPLICATION_CREDENTIALS:-nothing}:${GOOGLE_APPLICATION_CREDENTIALS:-/tmp/empty-GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - "127.0.0.1:3000:3000/tcp"
      - "127.0.0.1:8000:8000/tcp"
    command: serve
networks:
  default:
volumes:
  xdg-cache-home: { }
  nothing: { }
